Some improvements with grammar etc
Sol-Client/Client pull request #109
Opened 2022-11-27 20:36 UTC by intergrav

I read through and made changes by myself, and then I used Grammarly to double-check. Let me know if you think there are any errors.

2022-11-27 22:56 UTC, osfanbuff63 commented on README.md
>  ## Licence
```suggestion
## License
```

2022-11-28 08:52 UTC, TheKodeToad commented
Alreading :P.
I don't know how I missed it.

2022-11-28 09:02 UTC, TheKodeToad requested changes
Most changes are good, I just prefer UK spellings over US as somebody from England.

2022-11-28 09:02 UTC, TheKodeToad commented on README.md
> +- Quick Play Mod. Allows you to quickly join games at the press of a button (by default, "M"). The key opens a menu where you can search for games, navigating through them using the arrow keys. If yo
I'd prefer the UK spelling of these words.

2022-11-28 09:02 UTC, TheKodeToad commented on README.md
> +- Customisable font and color scheme.
Same here.

2022-11-28 09:02 UTC, TheKodeToad commented on README.md
> +This client has been tested by multiple people on Hypixel. On most popular servers, disallowed mods are disabled. There are unknown servers, but just disable the correct mods and you should be fine.
... and here.
Also, I don't think intended needs to be in the past tense.

2022-11-28 10:05 UTC, FelixFromDiscord commented
man ignoring the existence of english dialects 💀

2022-11-28 13:51 UTC, intergrav commented
💀 yup I can look at that once I’m home lmao

2022-11-28 23:32 UTC, intergrav commented on README.md
> +Some parts of the code use other licenses (such as code "borrowed" from other projects). If this is the case, it will be noted in a comment or another license file in the same directory.
In this case, the comma [is necessary](https://www.grammarly.com/blog/comma-before-and/).

2022-11-28 23:35 UTC, intergrav commented
Alright, I reverted words to use UK spelling and changed "intended" to "intend" :)

2022-11-29 08:47 UTC, TheKodeToad approved these changes

2022-11-29 08:48 UTC, merged